module.exports = {
    'facebookAuth' : {
        'clientID'      : '313784385487683', // your App ID
        'clientSecret'  : '93982b574f4fcd8a98f846acc6fbe3a8', // your App Secret
        'callbackURL'   : 'https://localhost:8000/auth/facebook/callback'
    },
    'twitterAuth' : {
        'consumerKey'       : 'RYgnUfRFxuXXr7Zz2fjQrMwz1',
        'consumerSecret'    : 'pNLlmvvpsPYiQDW10L50fkSiRmuTEDF68cL5GNa5SP4EoweOcH',
        'callbackURL'       : 'https://127.0.0.1:8000/auth/twitter/callback'
    },
    'googleAuth' : {
        'clientID'      : '616248451324-2096p9fobmes2uivdss382aro96hncu9.apps.googleusercontent.com',
        'clientSecret'  : 'r9juVlH7gpQQC26YyuaGxXK0',
        'callbackURL'   : 'https://127.0.0.1:8000/auth/google/oauth2callback'
    }

};